DATA_LOADER:
  TYPE : "Csv_Dataloader"
  DATA_PATH : "../dataset/mrs12m807.csv"

MODEL:
  ARCHITECTURES : ["SVM_Model", "DNN_Model", "DTree_Model", "KNN_Model","NaiveBayes_Model"]
  ARCHITECTURE: "SVM_Model"
  SAVE_PATH : "../pre_trained_models"
  CROSS_VAL_RESULTS_PATH : "../cross_val_results/"

  SVM:
    DECISION_FUNCTION_SHAPE : 'ovo'
    KERNEL : 'linear'
    C : 2
    GAMMA : 0.5
    PROBABILITY : True

  DNN:
    INPUT: 28
    HIDDEN_LAYER_1: 56
    HIDDEN_LAYER_2: 56
    HIDDEN_LAYER_3: 28
    OUTPUT: 2

    BATCH_SIZE: 20
    LR: 0.01
    EPOCH: 200

  DTREE:
    RANDOM_STATE: 30
    SPLITTER: "random"
    MAX_DEPTH: 5
    MIN_SAMPLES_LEAF: 10
    MIN_SAMPLES_SPLIT: 10

  KNN:
    N_NEIGHBORS: 15
    WEIGHTS: 'uniform'
    ALGORITHM: 'ball_tree'
    METRIC: 'minkowski'
